import './globals.css'
import Header from '@/Components/Header/Header'
import Footer from '@/Components/Footer/Footer'


export const metadata = {
  title: 'First Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-2xl mx-auto px-3 bg-slate-50">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
